export default class Conditions {
    conditions;
    
    constructor() {
        this.conditions = [
            "Avg Volume",
            "ATR",
            "Beta",
            "Book/sh",
            "Cash/sh",
            "Change",
            "Current Ratio",
            "Debt/Eq",
            "Dividend",
            "Dividend %",
            "Earnings",
            "EPS (ttm)",
            "EPS growth next Y",
            "EPS Next Q",
            "EPS Next Y",
            "EPS next 5Y",
            "EPS past 5Y",
            "EPS This Y",
            "EPS Q/Q",
            "Employees",
            "Forward P/E",
            "Gross Margin",
            "Income",
            "Insider Own",
            "Insider Trans",
            "Inst Trans",
            "Inst Own",
            "LT Debt/Eq",
            "Market Cap",
            "Oper. Margin",
            "Optionable",
            "Payout",
            "P/B",
            "P/C",
            "P/E",
            "P/FCF",
            "PEG",
            "Perf Week",
            "Perf Month",
            "Perf Quarter",
            "Perf Half Y",
            "Perf Year",
            "Perf YTD",
            "Prev Close",
            "Price",
            "Profit Margin",
            "Quick Ratio",
            "Recom",
            "Rel Volume",
            "ROA",
            "ROE",
            "ROI",
            "RSI (14)",
            "Sales",
            "Sales past 5Y",
            "Sales Q/Q",
            "Shs Float",
            "Shs Outstand",
            "Shortable",
            "Short Float",
            "Short Ratio",
            "SMA20",
            "SMA50",
            "SMA200",
            "Target Price",
            "Volatility (Week)",
            "Volatility (Month)",
            "Volume",
            "52W Range",
            "52W High",
            "52W Low",
          ];
    }
}